### ISSUE TITLE
Submit Datavalues with commas

### ISSUE THREAD

**Issue by 3mptystring** [TheMegaTB/BJS#110]
right now you can only give results with points as seperators, but whe need commas!

**Comment by TheMegaTB** [comment]
Conflicts with the input type though. This requires the input type to be changed to text and an additional event listener that cancels out all non-number character inputs.

**Comment by TheMegaTB** [comment]
Might be because of the localization of the browser

**Comment by TheMegaTB** [comment]
Confirmed
