### ISSUE TITLE
Groups cannot have the same name

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#131]

**Comment by TheMegaTB** [comment]
Actually now they can have :sweat_smile: changed from name-based identification to ID based one in the last commit 145d7e7e708f62bc42b16928bd930ef6f91e4e34

**Comment by NoahPeeters** [comment]
But it's more user-friendly if they cannot have the same name. Because it doesn't make sense to actually have multiple groups with the same name.
