### ISSUE TITLE
Next button is clickable on config home page 

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#132]
The next button in the top right corner is clickable after editing a contest.

**Comment by TheMegaTB** [comment]
Under what circumstances?

**Comment by TheMegaTB** [comment]
I can't seem to reproduce the 'next' button being shown on the main config page

**Comment by TheMegaTB** [comment]
Fixed by 5c5036e3e09231e4f35f86136723512b7bec9170
