### ISSUE TITLE
Add default URL structure

### ISSUE THREAD

**Issue by TheMegaTB** [TheMegaTB/BJS#17]
By default you get redirected to the config website.

If a default competition exists and is already configured you get redirected to it instead of the configuration page.

All competitions live @ https://ip/competition_name/login

Configuration UI is located @
https://ip/config

**Comment by NoahPeeters** [comment]
Funktioniert auch, dass wenn kein Wettberb läuft, man auf die config geleitet wird?

**Comment by TheMegaTB** [comment]
Ist ein TODO in der entsprechenden Datei, da die Daten im Frontend noch nicht verfügbar sind.
