### ISSUE TITLE
Save certificate status

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#21]

**Comment by TheMegaTB** [comment]
What's ment by that?

**Comment by NoahPeeters** [comment]
Wir haben uns gedacht, dass man speichern kann, welche Urkunden bereits erstellt wurden und welche nicht (als field im athlete). Wenn man dann urkunden erstellt, kann angezeigt werden, welche bereits erstellt wurden. So kann man Urkunden erstellen, ohne dass alle Schüler fertig sind ohne dabei durcheinander zu kommen.

**Comment by NoahPeeters** [comment]
backend is ready!

**Comment by NoahPeeters** [comment]
done!
