### ISSUE TITLE
Set Activation state of a discipline

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#25]

**Comment by NoahPeeters** [comment]
Mittlerweile haben wir das gar nicht mehr richtig. Die Stationsaccounts haben schreibrechte bei bestimmten Disziplinen und die werden dann auch nur angezeigt. Wenn man Disziplinen noch ausschalten könnte, wäre das irgendwie doppelt. Das selbe gilt auch für die "Get List of all/active Discipline" Card

**Comment by 3mptystring** [comment]
Aber du musst ja einmal feststellen welche Disziplinen angeboten werden und/oder ob sie elektronisch gemessen werden

**Comment by NoahPeeters** [comment]
Ich dachte, dass wir das mit den Elektronischen Messungen jetzt so machen, dass das als andere Sportart gewertet wird. Dann ist das von der Ui her einfacher. Und ich weiß nicht, inwieweit es noch sinnvoll ist die Disziplinen festzulegen. Ich würde es jetzt ehr so machen, dass man einen Account erstellen kann, und dann zwei Spalten hat. Links legt man fest, welche Stationsrechte und rechts welche Gruppenrechte der Account hat.

**Comment by 3mptystring** [comment]
Dann muss ich die Hälfte der UI neu machen ... Benötigt weitere Entscheidung

**Comment by NoahPeeters** [comment]
Ansonsten könnte man noch einen Butten machen, der für alle Gruppen und einen der für alle Sportarten einen Account erstellt und einen, der einen Adminaccoutn mit allen Rechten erstellt.

**Comment by NoahPeeters** [comment]
Ich würde folgendes vorschlagen. Dann wäre der Ablauf ungefähr 1. Athleten hinzufügen 2. Gruppenpasswörter  werden automatisch erstellt 3. Statiospasswörter werden für **alle Stationen** erstellt oder 3. Stationspasswörter werden für **alle ausgewählten Stationen** von der UI erstellt. Ich wäre für die zweite Variante. So kann man auswählen, welche Sportarten angeboten werden (-> Übersicht) aber während des Wettbewerbs wird diese Auswahl nicht weiter gebraucht (-> man muss es nicht in der db speichern)

**Comment by TheMegaTB** [comment]
@3mptystring die Hälfte der UI wurde sowieso schon geändert um diverse andere Änderungen zu kompensieren und man müsste lediglich die Struktur der config UI ändern, was der kleinere und wohl unkomplizierteste Teil der aktuellen UI ist.

**Comment by NoahPeeters** [comment]
Die ausgewählten Sportarten werden jetzt doch gespeichert. Dann kann man später darauf zugreifen, um z.B. in den Athleten zu speichern, welche Sportarten dieser machen kann.
