### ISSUE TITLE
Get Groups

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#26]

**Comment by NoahPeeters** [comment]
Im backend gibt es Gruppen in dem sinne gar nicht. Jeder Athlete hat nur einen String, mit dem er 'einer Gruppe zugeordnet wird'. z.B. kann man ihn nicht "aus einer Gruppe löschen" oder ähnliches. Ich würde fast so wie so sagen, dass Athleten nicht mehr bearbeitet werden können, wenn der Wettbewerb läuft. Das führt nur zu Verwirrung, weil das dann nur zu clients synchronisiert wird, die verbunden sind und es auf den anderen "fehlt". Deshalb würde ich vorschlagen, dass die Athleten vom frontend erstellt und den Gruppen zugewiesen werden und dann alle zusammen im server gespeichert werden.

**Comment by NoahPeeters** [comment]
Das selbe gilt dann natürlich auch für alle anderen Funktionen, die was mit Gruppen zutun haben.

**Comment by 3mptystring** [comment]
Im Frostend ist aber eine Strukturierung nach Gruppenzugehörigkeit er die Regel als die Ausnahme, es währe also durchaus häufig nötig, die Teilnehmer nach Gruppen sortiert ausgeben zu können

**Comment by TheMegaTB** [comment]
Es ist jedoch aktuell nichtmal möglich Athleten alle auszugeben. Du kannst nur die entschlüsseln, zu denen du den dazugehörigen Gruppenlogin hast. Der einzige Ort, wo eine Sortierung nach Gruppen sinnvoll ist, ist in der Ausgabe UI (die noch nicht existiert), und selbst dann ist es ein einfaches `const athletes = _.sortBy(athletes, 'group');`.

**Comment by NoahPeeters** [comment]
Da die Gruppen während der BJS nicht mehr benötigt werden, werden sie auch nicht gespeichert. Damit entfällt dann auch eine GetGroups function.
