### ISSUE TITLE
Get Access Codes

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#27]

**Comment by NoahPeeters** [comment]
Was genau ist damit gemeint? Was sollen Access Codes sein bzw. wofür soll man sie getten?

**Comment by 3mptystring** [comment]
Das sind sie Stations/gruppenleiter-codes die am ende der Konfiguration angezeigt werden sollen

**Comment by NoahPeeters** [comment]
Ich würde das andersherum machen. Also die UI erstellt einen Account. Ich würde dann eine Funktion machen, die den erstellten Account dann in der dB speichert. Weil nur das Feontend weiß ja am Anfang, welche Berechtigungen der Account hat.

**Comment by 3mptystring** [comment]
Ich hatte jetzt gedacht, dass die Accounts beim Abschluss der Konfiguration automatisch aufgrund der  eingetragenen Disziplinen & Gruppen erstellt werden. Ich dachte nicht dass die UI selbst Buttons zum Account zufügen hat

**Comment by NoahPeeters** [comment]
Ok. Ich würde dann solche Funktionen implementieren. Wenn wir irgendwann noch Zeit haben, können wir ja immer noch Buttons einfügen. Jetzt muss es aber erstmal funktionieren.
