### ISSUE TITLE
Set properties of an Athelte

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#28]

**Comment by NoahPeeters** [comment]
Ein Athlete ist einfach nur ein Objekt. Man kann dann einfach Athlete.first_name = "Kevin"; machen. Eine Liste mit allen Eigenschaften ist [hier](https://themegatb.github.io/BJS/Athlete.html) zu finden.

**Comment by 3mptystring** [comment]
Dann sei das damit gelöst
