### ISSUE TITLE
Handling von Daten in der UI

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#31]
Ich habe mal 2 Frauen zu der UI:

1. Wie ist das mit Variablen bei z.B. der config Datei. Kann man auf einer config Seite eine variable erstellen und auf der nächste darauf zugreifen bzw. wie kann man Daten zwischen den verschiedenen Seiten/Ansichten eines Ablaufes (config, eingäbe von werten) austauschen? Über eine Datenbank wäre ehr schlecht, weil da dann ja z.B. Funktionen, die mit dem Objekt verknüpft sind, verloren gehen.

2. Die Seiten werden ja erst gecached, wenn sie einmal geladen wurden, oder? wie ist dass dann in der praxis? Muss man alle Seiten der eingäbe UI einmal aufrufen? oder ist das nur eine Seite mit verschiedenen Ansichten (Anlehnung an die 1. Frage). Wenn nicht, ist es möglich das als eine Seite mit verschiedenen Ansichten zu handhaben? (Ich glaube so war das mal bei mir, als ich ein Projekt mit framework 7 gemacht habe).

**Comment by NoahPeeters** [comment]
Ein beispiel für die 1. Frage wäre z.B. bei der Input ui der login. Die eingelogten user, die dann ja als Accounts in einer variable gespeichert werden müssen, müssen ja auf allen Seiten der input ui erreichbar sein.

**Comment by TheMegaTB** [comment]
Zu 1.:
Es gibt sowohl im Server als auch im Client das Meteor Objekt. Dieses ist global und darin können Daten non-persistent gespeichert werden. Dabei ist zu beachten, dass dieses Objekt NICHT zwischen Client und Server geteilt ist sondern jeder sein eigenes besitzt. Mit anderen Worten: z.B. der Inhalt der config.json ist im Client also nicht verfügbar und müsste auf anderen Wegen erstmal an den Client übertragen und dort persistent gespeichert werden.
Da es Sinn ergibt Daten wie z.B. die angemeldeten Accounts oder die config Einstellungen persistent zu speichern gäbe es die Möglichkeit eine Technik namens localStorage zu benutzen. Diese ermöglicht es in hinreichend modernen Browsern Daten persistent, seitenübergreifend zu speichern.

Zu 2.:
Das Appcache package schreibt in http://localhost:3000/app.manifest automatisch alle Templates rein. Folglich werden beim ersten Aufruf irgendeiner Seite alle weiteren Seiten gecached. Es ist aktuell eine Seite mit verschiedenen Ansichten. Wenn man z.B. zwischen /contest/login und /contest wechselt findet kein vollständiger Reload statt sondern es wird lediglich der Inhalt der Seite ausgetauscht. Dabei wird auch nicht der komplette Inhalt der Seite getauscht sondern lediglich Teile (templates).

**Comment by NoahPeeters** [comment]
Dann machen wir das mit sessions: https://docs.meteor.com/api/session.html
