### ISSUE TITLE
Name der Software - RunItEasy?

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#32]
Bleibt der name jetzt eigentlich bei RunItEasy oder hat jemand einen besseren Vorschlag oder ein Gegenargument? Das wäre ja ganz interessant zu wissen, damit man solche Sachen wie ein Icon entwerfen kann (siehe [Logo](https://github.com/TheMegaTB/BJS/issues/29)).

**Comment by m-bra** [comment]
Also ich finde den Namen nach wie vor gut und passend und da wir ihn ja auch schon benutzen (Pflichtenheft!) sollte er beibehalten werden. Wirkliche andere Vorschlaege gibt es ja auch nicht

**Comment by NoahPeeters** [comment]
Da alle anscheinend alle mit dem Namen einverstanden sind, schließe ich den Issue.
