### ISSUE TITLE
F7 installation & setup

### ISSUE THREAD

**Issue by 3mptystring** [TheMegaTB/BJS#4]
tried & failed installing F7, want help from somebody who actually knows how to do it :(

**Comment by NoahPeeters** [comment]
Ich hab jetzt einfach mal einen wrapper hinzugefügt (siehe README). Einfach mal `cd meteor` und dann `meteor npm install` ausführen. Sollte dann funktionieren.

**Comment by TheMegaTB** [comment]
F7 CSS not working

**Comment by TheMegaTB** [comment]
Following this guide:
https://github.com/nobutakaoshiro/meteor-framework7-ios-material#how-to-use-it
the required stylesheets were added to the head section of the main.html (possibly needs to be replaced with a template ;) )
