### ISSUE TITLE
Add possibility to remove attempt in Input-UI

### ISSUE THREAD

**Issue by TheMegaTB** [TheMegaTB/BJS#40]
In case the value is nothing the attempt should get deleted and the following attempts should be moved one back

**Comment by TheMegaTB** [comment]
The best place to implement this would be the [updateMeasurement](https://github.com/TheMegaTB/BJS/blob/master/meteor/imports/ui/components/input/index.js#L176) function

**Comment by NoahPeeters** [comment]
Ist das nicht schon fertig? Ich dachte das hat Merlin eingebaut.

**Comment by TheMegaTB** [comment]
Ja sollte es. Hab ich bevor ich losgefahren bin fertig gemacht und alle
Bugs gefixt.

On Sun, Jan 1, 2017, 3:18 AM Noah Peeters <notifications@github.com> wrote:

Ist das nicht schon fertig? Ich dachte das hat Merlin eingebaut.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/TheMegaTB/BJS/issues/40#issuecomment-269889729>, or mute
the thread
