### ISSUE TITLE
Add little white blob around/behind number on input UI

### ISSUE THREAD

**Issue by TheMegaTB** [TheMegaTB/BJS#68]

**Comment by TheMegaTB** [comment]
The element of interest here is located at [imports/ui/components/input/index.html](https://github.com/TheMegaTB/BJS/blob/31c272a868fe97cc5f30c9f85b42de005eef7de8/meteor/imports/ui/components/input/index.html#L56)

**Comment by NoahPeeters** [comment]
Behind the 2/3 on the bottom of the screen:
![img_1329](https://cloud.githubusercontent.com/assets/7913185/21656334/0069d074-d2be-11e6-9689-290f80cc9682.PNG)
