### ISSUE TITLE
Output & Input UI Name not centered

### ISSUE THREAD

**Issue by NoahPeeters** [TheMegaTB/BJS#94]
The name slider in the navbar isn't catered if the device is smaller because of the fixed sizes of the navbar bottoms and the slider. That means for all devices with a lower resolution than 100px + 250px + 100px + padding ≈ 480px in width that the navbar text isn't centered.

**Comment by TheMegaTB** [comment]
How to fix it then?!

**Comment by TheMegaTB** [comment]
The problem is caused by the ".slider-title-wrapper" all parent elements are still centered and its children are centered in relation to it.
